#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# doas not required for some system commands
for command in mount umount sv su shutdown poweroff reboot ; do
	alias $command="doas $command"
done; unset command

se() { cd ~/.local/bin; $EDITOR $(fzf) ;}

# Verbosity and settings that you pretty much just always are going to want.
alias \
  ardour="pw-jack ardour8" \
	nmutt="neomutt ; pkill -RTMIN+12 dwmblocks" \
	doas="doas --" \
	cp="cp -i" \
	mv="mv -i" \
	rm="rm -i" \
	sxiv="nsxiv" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	ytd="yt-dlp --embed-metadata -i" \
	yta="yt-dlp -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
  scim="sc-im" \
  ikhal="ikhal-sync" \
	ls="ls -Alh --color=always --sort=extension" \
    lsn="ls -Alh --color=always --sort=time" \
	..="cd .." \
	...="cd ../.." \
	.3="cd ../../.." \
	.4="cd ../../../.." \
	.5="cd ../../../../.." \

# These common commands are just too long! Abbreviate them.
alias \
  ka="killall" \
  g="git" \
  xi="doas xbps-install -Su" \
  xr="doas xbps-remove -R" \
  xq="xbps-query" \
  xp="xbps-query -l | awk '{ print $2 } | xargs -n1 xbps-uhelper getpkgname'" \
  rel="xrdb merge ~/.config/x11/.Xresources" \
  audiodetect="pacmd unload-module module-udev-detect && pacmd load-module module-udev-detect" \
  lf="~/.local/bin/lfub" \
  nvidia-settings="nvidia-settings --config=~/.config/nvidia/nvidiarc" \

alias \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \

# Muh memes
alias \
	rr="curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash" \
