db_file			"~/.local/share/mpd/database"
log_file		"syslog"

music_directory		"~/Music"

playlist_directory	"~/.local/share/mpd/playlists"
state_file		"~/.local/share/mpd/state"
sticker_file		"~/.local/share/mpd/sticker.sql"

auto_update		"yes"
auto_update_depth	"0"
follow_inside_symlinks	"yes"
restore_paused		"yes"
port			"6600"

audio_output {
	type 		"pipewire"
	name 		"PipeWire Sound Server"
}

#audio_output {
#  type                    "fifo"
#  name                    "my_fifo"
#  path                    "/tmp/mpd.fifo"
#  format                  "48000:16:2"
#  buffer_time             "60000"
#}
